services:
  - type: web
    name: ordinechat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: HTTP_PROXY
        value: ""
      - key: HTTPS_PROXY
        value: ""
      - key: ALL_PROXY
        value: ""
      - key: http_proxy
        value: ""
      - key: https_proxy
        value: ""
      - key: all_proxy
        value: ""
